---

- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yml
  tasks:
    - name: Stop all cluster services
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - patroni
        - etcd
        - consul
        - haproxy
        - pgbouncer
        - keepalived
      ignore_errors: true

- hosts: all
  become: true
  gather_facts: true  # <-- ESTE ES EL CAMBIO (de false a true)
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include OS-specific variables for PG data dir
      include_vars: "vars/{{ ansible_os_family }}.yml"

    - name: Uninstall all related packages (RedHat)
      package:
        name:
          - "postgresql{{ postgresql_version }}-server"
          - "postgresql{{ postgresql_version }}"
          - "postgresql{{ postgresql_version }}-contrib"
          - "timescaledb-2-postgresql-{{ postgresql_version }}"
          - etcd
          - patroni
          - python3-psycopg2
          - haproxy
          - pgbouncer
          - keepalived
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Uninstall all related packages (Debian)
      apt:
        name:
          - "postgresql-{{ postgresql_version }}"
          - "postgresql-contrib-{{ postgresql_version }}"
          - "timescaledb-2-postgresql-{{ postgresql_version }}"
          - etcd
          - patroni
          - python3-psycopg2
          - haproxy
          - pgbouncer
          - keepalived
        state: absent
        purge: yes
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Remove all data, config, and log directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ postgresql_data_dir }}"
        - "{{ etcd_data_dir }}"
        - "{{ consul_data_path }}"
        - /etc/patroni
        - /etc/etcd
        - /etc/pgbouncer
        - /etc/haproxy
        - /etc/consul
        - /etc/keepalived
        - /var/log/postgresql
        - /var/log/patroni
        - /var/log/pgbouncer
        - /var/lib/pgbackrest
        - /etc/cron.d/pgbackrest
        - /etc/yum.repos.d/timescale_timescaledb.repo # For RedHat

    - name: Clean up systemd unit files
      command: systemctl daemon-reload

      